### PR TITLE
updated dependencies for security reasons

### PR DESCRIPTION
**Pull request by GarthDB**
Updated [marked](https://www.npmjs.com/package/marked) to fix [this security issue](https://www.npmjs.com/advisories/812).

### CODE REVIEW

**Comment by GarthDB** [comment]
Updated [standard](https://www.npmjs.com/package/standard)https://www.npmjs.com/package/standard) as well. With this, all dependencies are up to date.

**Comment by rsese** [comment]
Thanks for the contribution @GarthDB!

> Updated [standard](https://www.npmjs.com/package/standard) as well. With this, all dependencies are up to date.

We talked about this pull request and the team would add this to the list of items to review if you can   revert this `standard` update.  There's some past discussion about `standard` (we couldn't find a reference to it after a quick search) so it's a larger issue that we need talk about and would prefer if it wasn't updated here in your PR.  If you can revert that change so your PR is specific to the `marked` update, we can take a look.

**Comment by GarthDB** [comment]
@rsese I'll fix it.

**Comment by GarthDB** [comment]
@rsese ok, ready for review again.

**Comment by rsese** [comment]
Great thanks @GarthDB 👍   We can't promise a specific timeframe but someone from the team will take a look as soon as they can.

**Pull request merged**
